### ISSUE TITLE
Widget not loading

### ISSUE THREAD

**Issue by simonmaass** [dansmaculotte/vue-zendesk#10]
i cannot get the plugin to load...

If I comment out the line 25 in index.js "delete window.zE;" .... then it works and loads...

could I get some help pls?

**Comment by simonmaass** [comment]
@gaelreyrol any chance you could help me?

**Comment by gaelreyrol** [comment]
@simonmaass I am sorry, I am a very busy (covid-19 & co) so I am not able to provide a full support for now.

Can you provide the options you use ? A stacktrace ? A usage case so I can try to reproduce it ?

**Comment by simonmaass** [comment]
totally understand! same here - times are crazy!

I am trying to include this as a module in vuestorefront (https://github.com/DivanteLtd/vue-storefront)

`
import Zendesk from '@dansmaculotte/vue-zendesk'
Vue.use(Zendesk, {
        key: appConfig.zendesk.key,
        disabled: false,
        hideOnLoad: false,
        settings: {
          webWidget: {
            color: {
              theme: '#0D384D'
            },
            offset: { horizontal: '70px', vertical: '19px' },
            contactOptions: {
              chatLabelOffline: {
                enabled: false
              },
              chatLabelOnline: {
                enabled: true
              }
            },
            launcher: {
              chatLabel: {
                '*': 'Wir sind für Dich da.'
              }
            }
          }
        }
      })`

There are not errors in the console or anything - i can also see the script included in html... but zendesk is just not loading...

If i comment out line 25 "delete window.zE" then i loads...

**Comment by pa-bouly** [comment]
Hi @simonmaass  ! 
Can you update vue-zendesk to the new version ? (0.4.0) 
The package has been a bit rewrited and I think the issue should be fixed now, let us know.

**Comment by simonmaass** [comment]
with version 0.4.0 it works - great!
