### ISSUE TITLE
How to hide the webWidget  after script loaded?

### ISSUE THREAD

**Issue by Ale-cc** [dansmaculotte/vue-zendesk#2]
Hi~ 
As you konw,Loading scripts is async, How could I hide the webWidget after immediately?
`this.$zendesk('webWidget', 'hide');`

I don't want to show the icon when page loaded, click to show the webWidget.

**Comment by Zevran** [comment]
Hi,

It was not possible in a proper way so I published a new version that allows you to subscribe to script load event so hide you can hide just after.

The event `zendeskLoaded` is emitted on script load so you can subscribe to it with `this.$on` and I added an option `hideOnLoad` to automatically hide it after script loading.

Hope it will solve your problem !

**Comment by Zevran** [comment]
Can I close the issue @Ale-cc ?

**Comment by Zevran** [comment]
I consider the issue resolved, feel free to reopen it !

**Comment by Ale-cc** [comment]
@Zevran thanks. I resolved it via using Promise.
