### ISSUE TITLE
[Vue warn]: Error in mounted hook: "TypeError: window.zE is not a function"

### ISSUE THREAD

**Issue by thomergil** [dansmaculotte/vue-zendesk#23]
I get an immediate error when trying to call `this.$zendesk.show()`. I add it as follows:

```
Vue.use(Zendesk, {
  key: [...],
  disabled: false,
  hideOnLoad: true,
  settings: {
    webWidget: {
      color: {
        theme: '#78a300',
      },
    },
  },
});
```

And use it as follows:

```
//...
<script lang="ts">
import Vue from 'vue';

export default Vue.component('app-footer', {
  mounted() {
    this.$zendesk.show();
  },
});
```

Happy to supply more information, but maybe it's obvious what I am doing wrong. Thank you.

**Comment by thomergil** [comment]
I think I found the answer to my own question:

```
this.$zendesk.$on('loaded', () => {
  this.$zendesk.show();
});
```

**Comment by ak-akimoto-peraichi** [comment]
@thomergil 
My name is Hiroyuki, nice to meet you.

I am using nuxt-zendesk and this error was detected by sentry.
Since nuxt-zendesk uses vue-zendesk, I assume it is a similar error.

The version we are using is below, is the fix for this one internalized?

```javascript
// package-lock.json
"@dansmaculotte/nuxt-zendesk": {
      "version": "0.4.2",.
      "resolved": "https://registry.npmjs.org/@dansmaculotte/nuxt-zendesk/-/nuxt-zendesk-0.4.2.tgz",.
      "integrity": "sha512-4ilgq0x6TzvQBAOzEHzJXeb6zGQM2208ikDzbacCOY2A42H7VI9l1ml3AxT5e6ShXToB6WMcQ8SHRMlpWaSTmA==",
      "requires": {
        "@dansmaculotte/vue-zendesk":"^0.4.1"
      }
    },
    "@dansmaculotte/vue-zendesk": {
      "version": "0.4.4", }
      "resolved": "https://registry.npmjs.org/@dansmaculotte/vue-zendesk/-/vue-zendesk-0.4.4.tgz",.
      "integrity": "sha512-J1Q70y95QsVODpPtVkhw5Fk8TvJ/j9oHCoSyoJvUq0hg9fj5csB60nsXC4xYmfV+4WD/AT72oVr2rT3y8wp8gg=="
    },
```

Translated with www.DeepL.com/Translator (free version)

**Comment by rtouze** [comment]
Hello Hiroyuki,

The issue described by @thomergil is due to a wrong initialization of Zendesk widget. I can have multiple causes.
By the way, this plugin is compatible with Vue 2. I'm currently not able to make it compatible to vue 3  (I'm not using Zendesk anymore for the projects I work on).

**Comment by ak-akimoto-peraichi** [comment]
@rtouze 
Oh, right, my apologies.
Thank you for confirming.
