### ISSUE TITLE
Refused to connect to wss://widget-mediator.zopim.com/s/W/ws/xxxxxx/c/yyyyy because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy

### ISSUE THREAD

**Issue by ejpg** [dansmaculotte/vue-zendesk#36]
Im getting this error only in safari where xxx is an alphanumeric automatically generated and yyy is a numeric generated by the zendsesk script.
Reading [this documentation](https://developer.zendesk.com/documentation/classic-web-widget-sdks/web-widget/integrating-with-google/csp/) ive seen that to follow the CSP guidelines in the script tag we need to add the `nonce` prop but the library doesnt have this option. Is there a workaround for this???

**Comment by rtouze** [comment]
As far as I understand, your are looking for a way to add Zendesk widget <script> tag with the `nonce` attribute. The value of this attribute should correspond with what is written in the `Content-Security-Policy` header provided by your response.

I could add a `nonce` parameter to the `load` function of the plugin, hence you'll be able to load the widget with whatever random string provided by your server. Would it solve your issue?

**Comment by ejpg** [comment]
Yes! that would be awesome. In fact if i have time today i could even create the PR.
Hopefully this will fix the error, I havent tried adding the `nonce` attribute in my software since i only see this problem in production
