### ISSUE TITLE
400 error on /compose GET request

### ISSUE THREAD

**Issue by ClaudioVR** [dansmaculotte/vue-zendesk#7]
Hi,

I am relatively new to Vue. I have 2 questions in 1 really. 

Question 1.  When I do:  

` import Zendesk from '@dansmaculotte/vue-zendesk'  `

... I get the following error msg in VSCode: 

```
Could not find a declaration file for module '@dansmaculotte/vue-zendesk'. 'c:/Users/cluds/Desktop/AgentPAY_repo/AgentPay/node_modules/@dansmaculotte/vue-zendesk/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/dansmaculotte__vue-zendesk` if it exists or add a new declaration (.d.ts) file containing `declare module '@dansmaculotte/vue-zendesk';`ts(7016)
```

I am not using typescript on this project and I have declared the module in a .d.ts file. The error is still showing.

Question 2.

After configuring the widget as explained in your documentation, I noticed that the /compose GET request is failing with a 400 error. Do you have any idea as to what that could be?

Thanks

**Comment by lukemiller** [comment]
I am seeing the 400 error also.

**Comment by gaelreyrol** [comment]
@ClaudioVR Could you please describe more precisely the error you are encoutering when you try to import the package. I don't really how this error can be thrown if your project is not a Typescript project.

And for your second question, there is no request fired from this plugin to a `/compose` route so I think this question is out of package scope.

**Comment by 14nrv** [comment]
hi, very usefull plugin, thx :)

I got the same issue (`GET https://ekr.zdassets.com/compose/undefined 400`) when I use `this.$zendesk.load('XXX')` which is mentionned on the README. But with `Vue.use(Zendesk, {key: 'XXX', ...})` it s works, but I can t pass the key "dynamically" (via `this.$zendesk..load`) :/

**Comment by gaelreyrol** [comment]
Thanks @14nrv ! I will try to work on this ASAP !
